package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	graphmodel "github.com/wise/backend-interview-kit/graph/model"
	"github.com/wise/backend-interview-kit/internal/model"
)

// ---------------------------------------------------------------------------
// Job field resolvers (pre-implemented)
// These translate between the domain model and GraphQL types.
// ---------------------------------------------------------------------------

// Origin resolves the origin depot for a job.
func (r *jobResolver) Origin(ctx context.Context, obj *model.Job) (*model.Depot, error) {
	depot, err := r.repo.GetDepot(obj.OriginID)
	if err != nil {
		return nil, fmt.Errorf("fetching origin depot: %w", err)
	}
	return depot, nil
}

// Destination resolves the destination depot for a job.
func (r *jobResolver) Destination(ctx context.Context, obj *model.Job) (*model.Depot, error) {
	depot, err := r.repo.GetDepot(obj.DestinationID)
	if err != nil {
		return nil, fmt.Errorf("fetching destination depot: %w", err)
	}
	return depot, nil
}

// Driver resolves the assigned driver for a job (nil if unassigned).
func (r *jobResolver) Driver(ctx context.Context, obj *model.Job) (*model.Driver, error) {
	if obj.DriverID == nil {
		return nil, nil
	}
	driver, err := r.repo.GetDriver(*obj.DriverID)
	if err != nil {
		return nil, fmt.Errorf("fetching driver: %w", err)
	}
	return driver, nil
}

// CreatedAt formats the job creation time as an RFC3339 string.
func (r *jobResolver) CreatedAt(ctx context.Context, obj *model.Job) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// ---------------------------------------------------------------------------
// Query resolvers — drivers and driver are pre-implemented as examples.
// ---------------------------------------------------------------------------

// Drivers returns all drivers. Pre-implemented as a reference example.
func (r *queryResolver) Drivers(ctx context.Context) ([]*model.Driver, error) {
	return r.repo.ListDrivers()
}

// Driver returns a single driver by ID. Pre-implemented as a reference example.
func (r *queryResolver) Driver(ctx context.Context, id string) (*model.Driver, error) {
	driver, err := r.repo.GetDriver(id)
	if err != nil {
		return nil, fmt.Errorf("fetching driver: %w", err)
	}
	return driver, nil
}

// ---------------------------------------------------------------------------
// Task 1 — implement the jobs and job queries
// ---------------------------------------------------------------------------

// Jobs returns all jobs, optionally filtered by status and/or driver.
//
// TODO: implement this resolver.
//   - Delegate business logic to r.jobSvc
//   - The filter argument may be nil (return all jobs in that case)
func (r *queryResolver) Jobs(ctx context.Context, filter *model.JobsFilter) ([]*model.Job, error) {
	panic("not implemented: Jobs — see Task 1 in TASKS.md")
}

// Job returns a single job by ID, or nil if not found.
//
// TODO: implement this resolver.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.Job, error) {
	panic("not implemented: Job — see Task 1 in TASKS.md")
}

// ---------------------------------------------------------------------------
// Task 2 — implement the assignJob mutation
// ---------------------------------------------------------------------------

// AssignJob assigns a PENDING job to a driver.
//
// TODO: implement this resolver.
//   - Delegate business logic to r.jobSvc
//   - On a business rule violation, return a payload with UserError set rather
//     than returning a Go error (which would produce a top-level GraphQL error)
func (r *mutationResolver) AssignJob(ctx context.Context, input graphmodel.AssignJobInput) (*graphmodel.AssignJobPayload, error) {
	panic("not implemented: AssignJob — see Task 2 in TASKS.md")
}

// ---------------------------------------------------------------------------
// Task 3 — implement the updateJobStatus mutation
// ---------------------------------------------------------------------------

// UpdateJobStatus transitions a job to a new status.
//
// TODO: implement this resolver.
//   - Only the transitions defined in model.ValidTransitions are permitted
//   - On an invalid transition, return a payload with UserError set
func (r *mutationResolver) UpdateJobStatus(ctx context.Context, input graphmodel.UpdateJobStatusInput) (*graphmodel.UpdateJobStatusPayload, error) {
	panic("not implemented: UpdateJobStatus — see Task 3 in TASKS.md")
}

// ---------------------------------------------------------------------------
// Resolver wiring (do not edit)
// ---------------------------------------------------------------------------

func (r *Resolver) Job() JobResolver           { return &jobResolver{r} }
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
func (r *Resolver) Query() QueryResolver       { return &queryResolver{r} }

type jobResolver      struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver    struct{ *Resolver }
