// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/wise/backend-interview-kit/internal/model"
)

type AssignJobInput struct {
	JobID    string `json:"jobId"`
	DriverID string `json:"driverId"`
}

type AssignJobPayload struct {
	Job       *model.Job `json:"job,omitempty"`
	UserError *string    `json:"userError,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobStatusInput struct {
	JobID  string          `json:"jobId"`
	Status model.JobStatus `json:"status"`
}

type UpdateJobStatusPayload struct {
	Job       *model.Job `json:"job,omitempty"`
	UserError *string    `json:"userError,omitempty"`
}
